Class sample.Example Extends %RegisteredObject
{

Method MethodExample1() As %Status
{
    Write "Line 1"
    Write "Line 2"
    Write "Line 3"
    Write "Line 4"
    Write "Line 5"
    Write "Line 6"
    Write "Line 7"
    Write "Line 8"
    Write "Line 9"
    Write "Line 10"
    Write "Line 11"
    Write "Line 12"
    Write "Line 13"
    Write "Line 14"
    Write "Line 15"
    Write "Line 16"
    Write "Line 17"
    Write "Line 18"
    Write "Line 19"
    Write "Line 20"
    Write "Line 21"
    Write "Line 22"
    Write "Line 23"
    Write "Line 24"
    Write "Line 25"
    Write "Line 26"
    Write "Line 27"
    Write "Line 28"
    Write "Line 29"
    Write "Line 30"
    Write "Line 31"
    Write "Line 32"
    Write "Line 33"
    Write "Line 34"
    Write "Line 35"
    Write "Line 36"
    Write "Line 37"
    Write "Line 38"
    Write "Line 39"
    Write "Line 40"
    Write "Line 41"
    Write "Line 42"
    Write "Line 43"
    Write "Line 44"
    Write "Line 45"
    Write "Line 46"
    Write "Line 47"
    Write "Line 48"
    Write "Line 49"
    Write "Line 50"

    Quit $$$OK
}

Method MethodExample2() As %Status
{
    Set value1 = ##class(example.class).%New()
    Set value2 = ##class(example.class2).%New()

    Quit $$$OK
}

}
